dist: trusty
sudo: false
language: go
go:
- 1.8.x
go_import_path: github.com/terraform-providers/terraform-provider-cloudfoundry
install:
- sudo apt-get install jq
- pip install --upgrade --user awscli
- wget https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
- sudo dpkg -i vagrant_1.9.7_x86_64.deb
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
script:
- vagrant --help
branches:
  only:
  - master
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: q9uTZIYytbgK5yMzUWiw14i/DCMJ9LN9KcaJ0liB8woknI+3G/xGDbENz76uFP79ln9gMVUAZ5zPE1o2lQR3aMSS2M2wuMnfuF75WIpgpt83sbFB/dMiPfW11Twf3aNDikAgxH4wUymei2g7xAOMlaCtKLMXIIrUSzOe3f+HklmC30GYXjqxTnA2+9xjxFMwifqDH5nBiaPgLrRP9vN4czYn3rrVA6fuk/CIfZS393LMKZkrBZw05sN66A98x3TsvNWUb9vJhKjGN0UvFiVrgTlV0idbbKhHV0WWSVZIvZBxTe3YXTxWsxjF+DYbypgisLTMe0SCNOwoJgoLbZ2K4zfJn65JQ0mMqBvsn57IVW0wX0K3LkzFoB7W+xi67KEowFU0FFsEJa09ku0ledOapVOrFaVWeIIn0dpm9fdNzQCxcK9eWF3KSFm2PyfZwP9nWlFV9MlhEHk+MSmwyaQHhW7GyhWGFS6CAr/xfMxyES8hLaICtS6gsXfrHW7V+BJCQjZsKPyw0YE4WfsRF3qpXApl9aAzh+Ka2ofLXyXm+O6HC4J1Zko77u9NWYAy9pNDO0JdXwUWFybPBX9Ol77xAIXLOHuh4Bo54RKMhBgsrAWLpPhFk8QA+VN/mI/UG84KMdkxhV2WvK2rqjXNeugKqE9PJDhy3S/ywESwBmXwa/c=
  - secure: shB1nQ+MjJL64DJH/rxv80Obcp6izTOG9paMEbOfu2X3L3IE0qGlnkFXgpGanxl+t4EXIeSNulztpkki7XX1GX+9+Qfcs6QObKDWnJseA3NUjk7MFkuITW4QuLt+FRaw/TcKu5In59YpLqKpMQgV+uunSJZDrIFgH7BYbmPlxy2MziK/GY86rHMYMNhbw1YkWBB+PfoWdy1xhmfDG9YvnSxSgqlCqQPS7kj0PLGYBlpHi1lc0WvVMNV86QlarSi0ZMqvIElzhuI4+xUHPOeJjESpF5Zna956XrYMP1PrlGbzjdcC6d+CoMHCb9bzYWA/BQUSCxDXKm9ilAE6NFUWuDW8e3wCjbU8ItA9+C++WGFzxTljkrzl7TRBTiYETRhD9OqrL6GWSwAOFFbJtPnBrArt508hTyDgg5iQet0OU8+3GAztOw6gyKiY9zsgylyi9wOantRYr81vBSTAVzOBEoFrUFabfXyK4zIVCzUl8stwkJW5ZAol55ObHUSXub2/2T1e2QCS4UsG88YdbxXeq1ci17ZXGVaLuJJMNjPZiokoMd5X2oFhEfXMOG5fwXary9DsZObMZEzpKOukkf5EqTgVXthz12AAHX349yMiL+/E+gNickDBSswE1121NZkwt4kKUG7WYHowvQJyUifalX+wgiaSR5u6WZUBW2Q+rI4=
